### ISSUE TITLE
OAUTH integration or trust some header and auto create users

### ISSUE THREAD

**Issue by gitricko** [Eleven-Trading/TradeNote#135]
Does this app have a way that I can enable oauth or trust secure headers for auto user creation and login ?

**Comment by 7aklhz** [comment]
Can you tell me about your use case ? I imagine that you want to integrate TN inside your own app?

TN relies on parse platform and I cannot find any 0auth integration. It doesn't mean it's not doable but it would probably require quite some work.

**Comment by gitricko** [comment]
Not really… I am using a reverse proxy to secure my home network… (eg: pomerium-zero)

Look at this guide for guacamole
https://www.pomerium.com/docs/guides/guacamole

```
guacamole:
  container_name: guacamole_compose
  depends_on:
    - guacd
    - postgres
  environment:
    GUACD_HOSTNAME: guacd
    POSTGRES_DATABASE: guacamole_db
    POSTGRES_HOSTNAME: postgres
    POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
    POSTGRES_USER: guacamole_user
    # Enables HTTP header authentication
    HEADER_ENABLED: true
    # Adds expected HTTP header from incoming Pomerium requests
    HTTP_AUTH_HEADER: X-Pomerium-Claim-Email
  image: guacamole/guacamole
  networks:
    - guacnetwork_compose
  volumes:
    - ./record:/record:rw
  ports:
    - 8080/tcp
  restart: always
```

When this HEADER_ENABLED and HTTP_AUTH_HEADER is passed… It will trust the auth from pomerium and auto login the user from the email if it exist. I think the change is minor. If you can point me where to it… I can make the change too with help of chatGPT (it has been some time I did nodes development)
